---
title: "05_28_meet_Richard"
output: pdf_document
---

```{r setup, include=FALSE}
#rmarkdown::render("reports/05_28_meet_Richard.Rmd")
knitr::opts_chunk$set(echo = TRUE)
```

##Oh, priors

```{r age}
post <- post_age
year_eff <- apply(post$delta_j, 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge",
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,1,] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,2,] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
legend("bottomright", 
       legend = c("age",
                  "mA ~ normal( -8, 2)T[,0]", 
                  "aK ~ normal(0,3)", 
                  "bA ~ normal( 0 , 5 ) T[0,]",
                  "delta ~ dirichlet( alpha= 0.5)"), 
       col = white, 
       inset = c(0.01, 0.01))

# mA ~ normal( -8, 2)T[,0]; //global intercept
# to_vector(aK) ~ normal(0,3);
# for(d in 1:D) for(s in 1:2) bA[s,d] ~ normal( 0 , 5 ) T[0,];
# delta ~ dirichlet( alpha ); 0.5
```

```{r aget}
post <- post_aget
year_eff <- apply(post$delta_j, 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge",  
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,1,] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,2,] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
legend("bottomright", 
       legend = c("aget",
                  "mA ~ normal( 0, 3)T[,0]", 
                  "aK ~ normal(0,1)", 
                  "bA ~ normal(  0 , 3) T[0,]",
                  "delta ~ dirichlet( alpha= 0.5)"), 
       col = white, 
       inset = c(0.01, 0.01))
#   mA ~ normal( 0, 3)T[,0]; //global intercept
# 	to_vector(aK) ~ normal(0,1);
#   for(d in 1:D) for(s in 1:2) bA[s,d] ~ normal( 0 , 3 ) T[0,];
#   delta ~ dirichlet( alpha );
```

```{r age2}
post <- post_age2
year_eff <- apply(post$delta_j, 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge",  
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,1,] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,2,] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
legend("bottomright", 
       legend = c("age2",
                  "mA ~ normal( -8, 2)T[,0]", 
                  "aK ~ normal(0,3)", 
                  "bA ~ normal( 0 , 5 ) T[0,]",
                  "delta ~ dirichlet( alpha= 2)"), 
       col = white, 
       inset = c(0.01, 0.01))
# mA ~ normal( -8, 2)T[,0]; //global intercept
# to_vector(aK) ~ normal(0,3);
# for(d in 1:D) for(s in 1:2) bA[s,d] ~ normal( 0 , 5 ) T[0,];
# delta ~ dirichlet( alpha ); 2
```

```{r aget2}
post <- post_aget2
year_eff <- apply(post$delta_j, 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge",  
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,1,] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,2,] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
legend("bottomright", 
       legend = c("aget2",
                  "mA ~ normal( 0, 3)T[,0]", 
                  "aK ~ normal(0,1)", 
                  "bA ~ normal(  0 , 3) T[0,]",
                  "delta ~ dirichlet( alpha= 2)"), 
       col = white, 
       inset = c(0.01, 0.01))
#   mA ~ normal( 0, 3)T[,0]; //global intercept
# 	to_vector(aK) ~ normal(0,1);
#   for(d in 1:D) for(s in 1:2) bA[s,d] ~ normal( 0 , 3 ) T[0,];
#   delta ~ dirichlet( alpha );
```

```{r aged}
post <- post_aged
year_eff_1 <- apply(post$delta_j[,,1], 1, cumsum)
year_eff_2 <- apply(post$delta_j[,,2], 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge",  
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff_1),  post$mA[i] + post$bA[i,1,] * year_eff_1[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff_2),  post$mA[i] + post$bA[i,2,] * year_eff_2[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff_1, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff_2, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
legend("bottomright", 
       legend = c("aged",
                  "mA ~ normal( -8, 2)T[,0]", 
                  "aK ~ normal(0,3)", 
                  "bA ~ normal( 0 , 5 ) T[0,]",
                  "delta ~ dirichlet( alpha= 0.5)"), 
       col = white, 
       inset = c(0.01, 0.01))
#   mA ~ normal( -8, 2)T[,0]; //global intercept
# 	to_vector(aK) ~ normal(0,3);
#   for(d in 1:D) for(s in 1:2) bA[s,d] ~ normal( 0 , 5 ) T[0,];
#   for(s in 1:2) delta[s] ~ dirichlet( alpha );
```

```{r agedt}
post <- post_agedt
year_eff_1 <- apply(post$delta_j[,,1], 1, cumsum)
year_eff_2 <- apply(post$delta_j[,,2], 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge",  
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff_1),  post$mA[i] + post$bA[i,1,] * year_eff_1[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff_2),  post$mA[i] + post$bA[i,2,] * year_eff_2[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff_1, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff_2, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
legend("bottomright", 
       legend = c("agedt",
                  "mA ~ normal( 0, 3)T[,0]", 
                  "aK ~ normal(0,3)", 
                  "bA ~ normal( 0, 3 ) T[0,]",
                  "delta ~ dirichlet( alpha= 0.5)"), 
       col = white, 
       inset = c(0.01, 0.01))
#   mA ~ normal( -8, 2)T[,0]; //global intercept
# 	to_vector(aK) ~ normal(0,3);
#   for(d in 1:D) for(s in 1:2) bA[s,d] ~ normal( 0 , 5 ) T[0,];
#   for(s in 1:2) delta[s] ~ dirichlet( alpha );
```

##Comapare parameters

```{r bA}

plot(NULL, xlim = c(1,10), ylim = c(1,10), yaxt='n', xlab = "bA")
points( apply(post_age$bA, 2, mean), y = c(1,2), pch = 19, col = c(boycol, girlcol))
points( apply(post_aget$bA, 2, mean), y = c(3,4), pch = 19,col = c(boycol, girlcol))
points( apply(post_age2$bA, 2, mean), y = c(5,6), pch = 19,col = c(boycol, girlcol))
points( apply(post_aget2$bA, 2, mean), y = c(7,8), pch = 19,col = c(boycol, girlcol))
points( apply(post_aged$bA, 2, mean), y = c(9,10), pch = 19,col = c(boycol, girlcol))
lines( apply(post_age$bA, 2, PI)[,1], y = c(1,1), col = boycol)
lines( apply(post_aget$bA, 2, PI)[,1], y = c(3,3), col =boycol)
lines( apply(post_age2$bA, 2, PI)[,1], y = c(5,5), col =boycol)
lines( apply(post_aget2$bA, 2, PI)[,1], y = c(7,7), col =boycol)
lines( apply(post_aged$bA, 2, PI)[,1], y = c(9,9), col = boycol)
lines( apply(post_age$bA, 2, PI)[,2], y = c(2,2), col =  girlcol)
lines( apply(post_aget$bA, 2, PI)[,2], y = c(4,4), col = girlcol)
lines( apply(post_age2$bA, 2, PI)[,2], y = c(6,6), col = girlcol)
lines( apply(post_aget2$bA, 2, PI)[,2], y = c(8,8), col =girlcol)
lines( apply(post_aged$bA, 2, PI)[,2], y = c(10,10), col = girlcol)
axis(2, rep(c("age", "aget", "age2", "aget2", "aged"), each =2), at = c(1:10), las = 1)
```

```{r mAs}
plot(NULL, xlim = c(-15,0), ylim = c(1,5), yaxt='n', xlab = "mA")
points( mean(post_age$mA), y = 1, pch = 19, col = boycol)
points( mean(post_aget$mA), y = 2, pch = 19,col = boycol)
points( mean(post_age2$mA), y = 3, pch = 19,col = boycol)
points( mean(post_aget2$mA), y = 4, pch = 19,col = boycol)
points( mean(post_aged$mA), y = 5, pch = 19,col = boycol)
lines( PI(post_age$mA), y = c(1,1), col = boycol)
lines( PI(post_aget$mA), y = c(2,2), col =boycol)
lines( PI(post_age2$mA), y = c(3,3), col =boycol)
lines( PI(post_aget2$mA), y = c(4,4), col =boycol)
lines( PI(post_aged$mA), y = c(5,5), col = boycol)
axis(2, c("age", "aget", "age2", "aget2", "aged"), at = c(1:5), las = 1)

```

##ACTIVITIES
```{r activities }

par( mfrow = c( 1, 2))

#or
plot(apply(post_actt$aAM, 2, mean), 1:10, xlim = c(-1.6, 1.5),
     xlab = "Activity effect", ylab = "Activities", yaxt='n')
axis(2, colnames(d$amh), at = c(1:10), las = 1)
for (i in 1:10) lines(apply(post_actt$aAM, 2, PI)[,i], rep(i, each = 2))
abline(v = 0)

plot(apply(post_actth$aAM, 2, mean), 1:10, xlim = c(-1.6, 1.5),
     xlab = "Activity effect", ylab = "Activities", yaxt='n')
axis(2, colnames(d$amh), at = c(1:10), las = 1)
for (i in 1:10) lines(apply(post_actth$aAM, 2, PI)[,i], rep(i, each = 2))
abline(v = 0)
```
```{r plot act}
post <- post_actth

#age-sex specific knowledge with activities
# mA + aK[i,d] + bA[S[i], d] * sum (delta_j[ 1 : A[i] ] ) +dot_product( aAM[,d], AM[i]);
year_eff <- apply(post$delta_j, 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post$K, 2, mean), 
     xlab = "Age", ylab = "Knowledge", 
     pch = 19, col = alpha( d$sex_col, 0.6 ) )
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,1,] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:80) {
  lines(1:nrow(year_eff),  post$mA[i] + post$bA[i,2,] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
lines(1:nrow(year_eff_1),  mean(post$mA) + mean(post$bA[,1,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( boycol, alpha = 0.7))
lines(1:nrow(year_eff_2),  mean(post$mA) + mean(post$bA[,2,]) * apply(year_eff, 1, mean), type = "l", col = col.alpha( girlcol, alpha = 0.7))
```



##and activities
```{r bA act}

plot(NULL, xlim = c(1,10), ylim = c(1,8), yaxt='n', xlab = "bA")
points( apply(post_age$bA, 2, mean), y = c(1,2), pch = 19, col = c(boycol, girlcol))
points( apply(post_aget$bA, 2, mean), y = c(5,6), pch = 19,col = c(boycol, girlcol))
points( apply(post_acth$bA, 2, mean), y = c(3,4), pch = 19,col = c(boycol, girlcol))
points( apply(post_actth$bA, 2, mean), y = c(7,8), pch = 19,col = c(boycol, girlcol))
lines( apply(post_age$bA, 2, PI)[,1], y = c(1,1), col = boycol)
lines( apply(post_aget$bA, 2, PI)[,1], y = c(5,5), col =boycol)
lines( apply(post_acth$bA, 2, PI)[,1], y = c(3,3), col =boycol)
lines( apply(post_actth$bA, 2, PI)[,1], y = c(7,7), col = boycol)
lines( apply(post_age$bA, 2, PI)[,2], y = c(2,2), col =  girlcol)
lines( apply(post_aget$bA, 2, PI)[,2], y = c(6,6), col = girlcol)
lines( apply(post_acth$bA, 2, PI)[,2], y = c(4,4), col = girlcol)
lines( apply(post_actth$bA, 2, PI)[,2], y = c(8,8), col = girlcol)
axis(2, rep(c("age", "act", "aget", "actt"), each =2), at = c(1:8), las = 1)
```

```{r contrasts bAs}
plot(NULL, xlim = c(-2, 4), ylim = c(1,4), yaxt='n')
points(mean(post_aget$bA[,1,] - post_aget$bA[,2,]), 3, pch = 19, col = "cornflowerblue")
points(mean(post_actth$bA[,1,] - post_actth$bA[,2,]), 4, pch = 19, col ="cornflowerblue")
points(mean(post_age$bA[,1,] - post_age$bA[,2,]), 1, pch = 19, col ="cornflowerblue")
points(mean(post_acth$bA[,1,] - post_acth$bA[,2,]), 2, pch = 19, col ="cornflowerblue")
lines(PI(post_aget$bA[,1,] - post_aget$bA[,2,]), c(3,3), col = "cornflowerblue")
lines(PI(post_actth$bA[,1,] - post_actth$bA[,2,]), c(4,4), col = "cornflowerblue")
lines(PI(post_age$bA[,1,] - post_age$bA[,2,]), c(1, 1), col = "cornflowerblue")
lines(PI(post_acth$bA[,1,] - post_acth$bA[,2,]), c(2, 2), col = "cornflowerblue")
abline(v = 0, col = "grey")
axis(2, c("age", "acth", "aget", "actth"), at = c(1:4), las = 1)
```


## Dimensions
```{r compare dimensions}
plot(waics)
```
```{r 2 dim knowledge}
post_d <- postd_2

#check the correlation between dimensions
plot(apply( post_d$K[,,1], 2, mean), apply( post_d$K[,,2], 2, mean),
     xlab = "K 1", ylab = "K 2",col = d$sex_col)
```

```{r 3 dim knowledge}
post_d <- postd_3

#check the correlation between dimensions
par( mfrow = c( 1,3))

plot(apply( post_d$K[,,1], 2, mean), apply( post_d$K[,,2], 2, mean),
     xlab = "K 1", ylab = "K 2",col = d$sex_col)
plot(apply( post_d$K[,,1], 2, mean), apply( post_d$K[,,3], 2, mean),
     xlab = "K 1", ylab = "K 3",col = d$sex_col)
plot(apply( post_d$K[,,2], 2, mean), apply( post_d$K[,,3], 2, mean),
     xlab = "K 2", ylab = "K 3",col = d$sex_col)
```

```{r 4 dim knowledge}
post_d <- postd_4
par( mfrow = c( 2,3))
#knowledge

plot(apply( post_d$K[,,1], 2, mean), apply( post_d$K[,,2], 2, mean),
     xlab = "K 1", ylab = "K 2",col = d$sex_col)
plot(apply( post_d$K[,,1], 2, mean), apply( post_d$K[,,3], 2, mean),
     xlab = "K 1", ylab = "K 3",col = d$sex_col)
plot(apply( post_d$K[,,2], 2, mean), apply( post_d$K[,,3], 2, mean),
     xlab = "K 2", ylab = "K 3",col = d$sex_col)
plot(apply( post_d$K[,,1], 2, mean), apply( post_d$K[,,4], 2, mean),
     xlab = "K 1", ylab = "K 4",col = d$sex_col)
plot(apply( post_d$K[,,4], 2, mean), apply( post_d$K[,,3], 2, mean),
     xlab = "K 4", ylab = "K 3",col = d$sex_col)
plot(apply( post_d$K[,,2], 2, mean), apply( post_d$K[,,4], 2, mean),
     xlab = "K 2", ylab = "K 4",col = d$sex_col)
```


```{r 3 dimension age effects}
post_d <- postd_3

#check the correlation between dimensions
par( mfrow = c( 1,3))
#Age effect#
#dimension specific deltas
year_eff <- apply(post_d$delta_j[,,1], 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post_d$K[,,1], 2, mean), 
     xlab = "Age", ylab = "Knowledge", col = d$sex_col )
for (i in 1:50) {
  lines(1:nrow(year_eff),  post_d$mA[i,1] + post_d$bA[i,1,1] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:50) {
  lines(1:nrow(year_eff),  post_d$mA[i,1] + post_d$bA[i,2,1] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
year_eff <- apply(post_d$delta_j[,,2], 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post_d$K[,,2], 2, mean), 
     xlab = "Age", ylab = "Knowledge", col = d$sex_col )
for (i in 1:50) {
  lines(1:nrow(year_eff),  post_d$mA[i,2] + post_d$bA[i,1,2] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:50) {
  lines(1:nrow(year_eff),  post_d$mA[i,2] + post_d$bA[i,2,2] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
year_eff <- apply(post_d$delta_j[,,3], 1, cumsum)
plot(d$A[ d$A <= 50 ], apply(post_d$K[,,3], 2, mean), 
     xlab = "Age", ylab = "Knowledge", col = d$sex_col )
for (i in 1:50) {
  lines(1:nrow(year_eff),  post_d$mA[i,3] + post_d$bA[i,1,3] * year_eff[,i], type = "l", col = col.alpha( boycol, alpha = 0.1))
}
for (i in 1:50) {
  lines(1:nrow(year_eff),  post_d$mA[i,3] + post_d$bA[i,2,3] * year_eff[,i], type = "l", col = col.alpha( girlcol, alpha = 0.1))
}
```
```{r difficulty dimensions}
par( mfrow = c( 1, 3))
plot(apply( post_d$b_l[,,1], 2, mean), apply( post_d$b_l[,,2], 2, mean),
     xlab = "K 1", ylab = "K 2",col = d$color_l)
plot(apply( post_d$b_l[,,1], 2, mean), apply( post_d$b_l[,,3], 2, mean),
     xlab = "K 1", ylab = "K 3",col = d$color_l)
plot(apply( post_d$b_l[,,2], 2, mean), apply( post_d$b_l[,,3], 2, mean),
     xlab = "K 2", ylab = "K 3",col = d$color_l)
```

```{r qn parameters dimensions}
par( mfrow = c( 1, 3))
#check knowledge and questions parameters
#1st dimension
Ks_1 <- apply(post_d$K[,,1], 2, mean)
a_ls_1 <- apply(post_d$a_l[,,1], 2, mean)
b_ls_1 <- apply(post_d$b_l[,,1], 2, mean)
curve(inv_logit(a_ls_1[1] * ( x - b_ls_1[1])), 
      xlim = c(-7, 5), ylim = c(0, 1), 
      xlab = "knowledge dimension 1", ylab = "p correct answer",
      col = col.alpha("lightblue", 0.2))
for(i in 1: length(a_ls_1)){
  curve(inv_logit(a_ls_1[i] * ( x - b_ls_1[i])), col = col.alpha(d$color_l[i], 0.2), add = TRUE)
}
points(Ks_1, rep(0.5, length(Ks_1)),col = col.alpha("cornflowerblue", 0.7))  

#2nd dimension
Ks_2 <- apply(post_d$K[,,2], 2, mean)
a_ls_2 <- apply(post_d$a_l[,,2], 2, mean)
b_ls_2 <- apply(post_d$b_l[,,2], 2, mean)
curve(inv_logit(a_ls_2[1] * ( x - b_ls_2[1])), 
      xlim = c(-7, 5), ylim = c(0, 1), 
      xlab = "knowledge dimension 2", ylab = "p correct answer",
      col = col.alpha("lightblue", 0.2))
for(i in 1: length(a_ls_2)){
  curve(inv_logit(a_ls_2[i] * ( x - b_ls_2[i])), col = col.alpha(d$color_l[i], 0.2), add = TRUE)
}
points(Ks_2, rep(0.5, length(Ks_2)),col = col.alpha("cornflowerblue", 0.7))  

#3rd dimension
Ks_3 <- apply(post_d$K[,,3], 2, mean)
a_ls_3 <- apply(post_d$a_l[,,3], 2, mean)
b_ls_3 <- apply(post_d$b_l[,,3], 2, mean)
curve(inv_logit(a_ls_3[1] * ( x - b_ls_3[1])), 
      xlim = c(-7, 5), ylim = c(0, 1), 
      xlab = "knowledge dimension 3", ylab = "p correct answer",
      col = col.alpha("lightblue", 0.2))
for(i in 1: length(a_ls_3)){
  curve(inv_logit(a_ls_3[i] * ( x - b_ls_3[i])), col = col.alpha(d$color_l[i], 0.2), add = TRUE)
}
points(Ks_3, rep(0.5, length(Ks_1)),col = col.alpha("cornflowerblue", 0.7))  
plot(apply( post_d$b_l[,,1], 2, mean), apply( post_d$b_l[,,2], 2, mean),
     xlab = "K 1", ylab = "K 2",col = d$color_l)
plot(apply( post_d$b_l[,,1], 2, mean), apply( post_d$b_l[,,3], 2, mean),
     xlab = "K 1", ylab = "K 3",col = d$color_l)
plot(apply( post_d$b_l[,,2], 2, mean), apply( post_d$b_l[,,3], 2, mean),
     xlab = "K 2", ylab = "K 3",col = d$color_l)

par( mfrow = c( 1, 1))
```

```{r difficult items}
b_ls <- apply(post_aget$b_l, 2, mean)
print("one dimension model")
colnames(d$Y_l)[which(b_ls <=max(sort(b_ls)[1:10]))]
print("three dimensions model_2")
colnames(d$Y_l)[which(b_ls_2 <=max(sort(b_ls_2)[1:10]))]
print("three dimensions model_1")
colnames(d$Y_l)[which(b_ls_1 <=max(sort(b_ls_1)[1:10]))]
print("three dimensions model_3")
colnames(d$Y_l)[which(b_ls_3 <=max(sort(b_ls_3)[1:10]))]

```